// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfpwsktxkztyqsyvfepy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmcHdza3R4a3p0eXFzeXZmZXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMjc0OTEsImV4cCI6MjA1OTgwMzQ5MX0.xLxmPOtbksUiU8wY0WfZ36E04MPQvuWRmnmYJcnNoQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);